apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: busybox-line
  namespace: flux-workspace
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: source-repository
    namespace: flux-workspace
  path: ./clusters/busybox-stockholm/sets/busybox-line
  prune: true
  decryption:
    provider: sops
  dependsOn:
  - name: busybox-stockholm-infra
